### ISSUE TITLE
Raspberry PI rebooting when executing rr.forward

### ISSUE THREAD

**Issue by Nick-B31** [simonmonk/raspirobotboard2#5]
When I try to execute the below the Raspberry Pi crashes.  I have installed the appropriate libraries and followed the readme.

>from rrb2 import *
>rr = RRB2()
>rr.forward()

Using a Rapsberry Pi Model B Revision 2.0 (512MB) with an Edimax EW-7811Un USB Wi-Fi adapter with the RaspiRobot v2 board and two 6v DC motors.

I am able to control the LEDs with these commands: 

>rr.set_led1(1)
>rr.set_led2(1)
>rr.set_led1(0)
>rr.set_led2(0)

Thanks in advance.

**Comment by simonmonk** [comment]
What are you using for a battery pack?


On 15 Jun 2015, at 21:52, Nick-B31 <notifications@github.com> wrote:

> When I try to execute the below the Raspberry Pi crashes. I have installed the appropriate libraries and followed the readme.
> 
> from rrb2 import *
> rr = RRB2()
> rr.forward()
> 
> Using a Rapsberry Pi Model B Revision 2.0 (512MB) with an Edimax EW-7811Un USB Wi-Fi adapter with the RaspiRobot v2 board and two 6v DC motors.
> 
> Thanks in advance.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Simon Monk. http://www.simonmonk.org

**Comment by Nick-B31** [comment]
Thank you very much for the quick response! I am powering it from the Raspberry Pi USB power. Nothing connected to the power terminals on the RaspiRobot Board.

**Comment by simonmonk** [comment]
OK, that's your problem. You need a battery pack or 9-12V power supply connected the the RRBv2 screw terminals. 

Si.


On 15 Jun 2015, at 22:03, Nick-B31 <notifications@github.com> wrote:

> Thank you very much for the quick response! I am powering it from the Raspberry Pi USB power. Nothing connected to the power terminals on the RaspiRobot Board.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Simon Monk. http://www.simonmonk.org

**Comment by Nick-B31** [comment]
I had a spare PSU available. I've used one of the 12v power lines and GND on it.

I am able to get both motors to "hum" with this command now instead of crashing:

>rr.set_motors(0.5, 1, 0.5, 0)

Running the below script I am able to get the motors to hum at the "Is one motor going forwards at half speed?" question and the motors for a split second will go in the direction they are supposed to at what seems like a reasonable speed. I have verified they move freely otherwise.

>#Python 2
>import rrb2 as rrb
>import time
>#import ex_8x8_pixels
>rr = rrb.RRB2(revision=2)
>def confirm(question):
 >   answer = raw_input(question)
>def test_motors():
>    rr.set_motors(0, 0, 0, 0)
>    confirm("Are Both motors stopped?")
>    rr.set_motors(1, 0, 1, 0)
>    confirm("Are Both motors going forwards?")
>    rr.set_motors(0.5, 0, 1, 0)
>    confirm("Is one motor going forwards at half speed?")
>    rr.set_motors(1, 1, 1, 1)
>    confirm("Are both motors going backwards?")
>    rr.set_motors(0, 0, 0, 0)
>    confirm("Are the motors off now?")
>test_motors()


Results: 

1. Are Both motors going forwards? - Nothing
2. Is one motor going forwards at half speed? - Humming and Left Motor moves slight when moving on to next command/question
3. Are both motors going backwards? - Nothing

Thanks again

**Comment by Nick-B31** [comment]
The problem of getting the motors to turn/stop humming still persists after moving to 9v wall wart. If you'd like to treat this as a separate problem I am happy to mark this issue closed as switching over to either 9v or 12v PSU solved the problem of the Rpi crashing.
