### ISSUE TITLE
Compatible with RPi B+?

### ISSUE THREAD

**Issue by positlabs** [simonmonk/raspirobotboard2#7]
Is this board compatible with the RPi B+?

**Comment by simonmonk** [comment]
Yes.

Si.

On 27 Jul 2015, at 01:16, Josh Beckwith notifications@github.com wrote:

> Is this board compatible with the RPi B+?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Simon Monk. http://www.simonmonk.org

**Comment by positlabs** [comment]
Woo! Thanks!
